config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :leads do
    collection { post :import }
    collection { post :email }
  end

  concern :pageable do
    get 'page/:page', action: :index, on: :collection
  end

  mount Sidekiq::Web => '/sidekiq'

  root 'pages#home'
end

app/models/lead.rb
class Lead < ActiveRecord::Base

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Lead.create! row.to_hash
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  def index
    @leads = Lead.all
  end

  def import
    Lead.import(params[:file])
    redirect_to leads_path, notice: "Leads imported."
  end

  def email
    leads_array = Lead.where(phase: params[:phase])
    campaign = params[:campaign]
    leads_array = leads_array.pluck(:id)
    CampaignWorker.perform_async(leads_array, campaign)
    redirect_to leads_path, notice: "Leads scheduled for email."
  end

  # GET /leads/1
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  def create
    @lead = Lead.new(lead_params)

    if @lead.save
      redirect_to @lead, notice: 'Lead was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /leads/1
  def update
    if @lead.update(lead_params)
      redirect_to @lead, notice: 'Lead was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /leads/1
  def destroy
    @lead.destroy
    redirect_to leads_url, notice: 'Lead was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def lead_params
      params[:lead]
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end

  def meta_description(page_meta_description)
    content_for(:meta_description) { page_meta_description }
  end

  def heading(page_heading)
    content_for(:heading) { page_heading }
  end

  def link_to_all_favicons
    '<link href="speeddial-160x160.png" rel="icon" type="image/png" />
    <link href="apple-touch-icon-228x228-precomposed.png" rel="apple-touch-icon-precomposed" sizes="228x228" type="image/png" />
    <link href="apple-touch-icon-152x152-precomposed.png" rel="apple-touch-icon-precomposed" sizes="152x152" type="image/png" />
    <link href="apple-touch-icon-144x144-precomposed.png" rel="apple-touch-icon-precomposed" sizes="144x144" type="image/png" />
    <link href="apple-touch-icon-120x120-precomposed.png" rel="apple-touch-icon-precomposed" sizes="120x120" type="image/png" />
    <link href="apple-touch-icon-114x114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114" type="image/png" />
    <link href="apple-touch-icon-76x76-precomposed.png" rel="apple-touch-icon-precomposed" sizes="76x76" type="image/png" />
    <link href="apple-touch-icon-72x72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72" type="image/png" />
    <link href="apple-touch-icon-60x60-precomposed.png" rel="apple-touch-icon-precomposed" sizes="60x60" type="image/png" />
    <link href="apple-touch-icon-57x57-precomposed.png" rel="apple-touch-icon-precomposed" sizes="57x57" type="image/png" />
    <link href="favicon-196x196.png" rel="icon" sizes="196x196" type="image/png" />
    <link href="favicon-160x160.png" rel="icon" sizes="160x160" type="image/png" />
    <link href="favicon-96x96.png" rel="icon" sizes="96x96" type="image/png" />
    <link href="favicon-64x64.png" rel="icon" sizes="64x64" type="image/png" />
    <link href="favicon-32x32.png" rel="icon" sizes="32x32" type="image/png" />
    <link href="favicon-24x24.png" rel="icon" sizes="24x24" type="image/png" />
    <link href="favicon-16x16.png" rel="icon" sizes="16x16" type="image/png" />
    <link href="favicon.ico" rel="icon" type="image/x-icon" />
    <link href="favicon.ico" rel="shortcut icon" type="image/x-icon" />'.html_safe
  end

  def humanize_boolean(input)
    input ||= ''
    case input.to_s.downcase
    when 't', 'true'
      'Yes'
    else
      'No'
    end
  end

  def css_for_boolean(input)
    if input
      'success'
    else
      'danger'
    end
  end
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_disqus_comments_snippet.html.erb
<% if ENV['DISQUS_SHORT_NAME'].present? %>
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = '<%= ENV["DISQUS_SHORT_NAME"] %>';
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>
  Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a>
</noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
<% end %>

app/views/layouts/_disqus_count_snippet.html.erb
<% if ENV['DISQUS_SHORT_NAME'].present? %>
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = '<%= ENV["DISQUS_SHORT_NAME"] %>';
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <% unless key == :timedout %>
    <%= content_tag :div, class: "alert alert-dismissable alert-#{key}" do -%>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
      <%= msg %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<p class="text-muted">&copy; 2014 marketing - All rights reserved</p>

app/views/layouts/_google_analytics_snippet.html.erb
<script type="text/javascript">
  var _gaq = _gaq || [];
<% if ENV['GOOGLE_ANALYTICS_UA'].present? %>
  _gaq.push(['_setAccount', '<%= ENV["GOOGLE_ANALYTICS_UA"] %>']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
<% end %>
</script>

app/views/layouts/_google_analytics_tracker.html.erb
<script type="text/javascript">
  // This is added in the body to track both turbolinks and regular hits.
  _gaq.push(['_trackPageview']);
</script>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'marketing', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li>
  <%= link_to 'Sidekiq dashboard', '/sidekiq' %>
</li>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
  <title><%= yield :title %></title>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= yield :meta_description %>" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js',
                             'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= link_to_all_favicons %>
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/json3/3.3.0/json3.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
  <![endif]-->
  <%= render 'layouts/google_analytics_snippet' %>
</head>

<body>
  <%= render 'layouts/google_analytics_tracker' %>
  <header>
    <%= render 'layouts/navigation' %>
  </header>

  <main role="main" class="container">
    <div class="page-header">
      <h1><%= yield :heading %></h1>
    </div>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </main>

  <footer>
    <hr />
    <div class="container">
      <%= render 'layouts/footer' %>
    </div>
  </footer>

  <%= render 'layouts/disqus_count_snippet' %>
</body>
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<h1>Leads</h1>

<div class="">
  <%= form_tag import_leads_path, class: "form-inline", multipart: true do %>
    <div class="input-group">
      <span class="input-group-addon">File:</span>
      <%= file_field_tag :file, class: "form-control" %>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  <% end %>
  <br>
  <%= form_tag email_leads_path, class: "form-inline", multipart: true do %>
    <div class="input-group">
      <span class="input-group-addon">Phase:</span>
      <input type="text" class="form-control" id="phase" name="phase" placeholder="Phase">
    </div>
    <div class="input-group">
      <span class="input-group-addon">Campaign:</span>
      <input type="text" class="form-control" id="campaign" name="campaign" placeholder="Campaign">
    </div>
    <button type="submit" class="btn btn-default">Email</button>
  <% end %>
</div>
<br>
<br>
<div class="">
  <table id="leads" class="table table-condensed table-hover">
    <thead>
      <tr>
        <th>Phase</th>
        <th>First</th>
        <th>Last</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @leads.each do |lead| %>
        <tr>
          <td><%= lead.phase %></td>
          <td><%= lead.first_name %></td>
          <td><%= lead.last_name %></td>
          <td><%= lead.email %></td>
          <td><%= link_to 'Show', lead %></td>
          <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
          <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

<br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>

app/views/pages/home.html.erb
<%
  title 'Marketing'
  meta_description '...'
  heading 'Production Sense Marketing Home'
%>

<div class="row">
  <div class="col-sm-9">
      
  </div>
</div>